write errors to stderr

diff --git a/.local/bin/bt b/.local/bin/bt
--- a/.local/bin/bt
+++ b/.local/bin/bt
@@ -20,7 +20,7 @@ case $1 in
         cmd="disconnect"
         ;;
     *)
-        echo "Invalid argument: ${1}"
+        echo "Invalid argument: ${1}" >&2
         exit 1
         ;;
 esac
diff --git a/.local/bin/scrn b/.local/bin/scrn
--- a/.local/bin/scrn
+++ b/.local/bin/scrn
@@ -28,7 +28,7 @@ case $external_pos in
         exit
         ;;
     *)
-        echo "Invalid argument: ${1}"
+        echo "Invalid argument: ${1}" >&2
         exit 1
         ;;
 esac
diff --git a/.local/bin/wifi b/.local/bin/wifi
--- a/.local/bin/wifi
+++ b/.local/bin/wifi
@@ -10,7 +10,7 @@ case $1 in
         exit ${prev_exit_code:-$?}
         ;;
     *)
-        echo "Invalid argument: ${1}"
+        echo "Invalid argument: ${1}" >&2
         exit 1
         ;;
 esac
